### PR TITLE
Changes to Schema + Sitemap support

### PR DESCRIPTION
**Pull request by shahthepro**

### CODE REVIEW

**Review by franckc — APPROVED** [review]
Nice work. LGTM

**Comment by franckc** [comment]
@shahthepro What are the steps for deploying this PR to staging? Do we need to wipe out the current articles data in the DB or can we just deploy and the existing articles will be slotted into the new schema?

@rolandpo @nickick  I assume that when we merge and deploy this, some minor adjustments will be needed on the client side to pull the data using this new schema?

**Review by nickick — APPROVED** [review]
Changes look good to me. @franckc yes we'll need to update where we pull API data from for the articles to work on website-frontend but that should be easy.

**Comment by franckc** [comment]
Alright! 

@shahthepro please feel free to merge and deploy to the staging strapi

@rolandpo can you update the client to query data using this updated schema?

**Comment by shahthepro** [comment]
@franckc I'm still working on some more changes to the schema but I can open a different PR for that today so that Roland isn't blocked by it

**Pull request merged**
